app_name = "xi102 collection"

# possible values: DEBUG, INFO, WARNING, ERROR, FATAL
log_level = "DEBUG"

[mysql]
ip = "127.0.0.1"
port = 3306
user = "root"
password = 123456
database = "collection"

[redis]
ip = "127.0.0.1"
port = 7381


[server]
protocols = ["http", "https", "port"]
ports = [10000, 10001, 10002]

